const imagesByCategory = {
  top: [
    './images/furniture/chair/1.jpg',
    './images/furniture/bed/1.jpg',
    './images/furniture/sofa/1.jpg',
    './images/furniture/dining/1.jpg',
    './images/furniture/table/1.jpg',
    './images/furniture/chair/2.jpg',
    './images/furniture/bed/2.jpg',
    './images/furniture/sofa/2.jpg',
    './images/furniture/dining/2.jpg',
    './images/furniture/table/2.jpg',
    './images/furniture/chair/3.jpg',
    './images/furniture/bed/3.jpg',
    './images/furniture/sofa/3.jpg',
    './images/furniture/dining/3.jpg',
    './images/furniture/table/3.jpg',
  ],
  featured: [
    './images/furniture/chair/4.jpg',
    './images/furniture/bed/4.jpg',
    './images/furniture/sofa/4.jpg',
    './images/furniture/dining/4.jpg',
    './images/furniture/table/4.jpg',
    './images/furniture/chair/5.jpg',
    './images/furniture/bed/5.jpg',
    './images/furniture/sofa/5.jpg',
    './images/furniture/dining/5.jpg',
    './images/furniture/table/5.jpg',
    './images/furniture/chair/6.jpg',
    './images/furniture/bed/6.jpg',
    './images/furniture/sofa/6.jpg',
    './images/furniture/dining/6.jpg',
    './images/furniture/table/6.jpg',
  ],
  sale: [
    './images/furniture/chair/7.jpg',
    './images/furniture/bed/7.jpg',
    './images/furniture/sofa/7.jpg',
    './images/furniture/dining/7.jpg',
    './images/furniture/table/7.jpg',
    './images/furniture/chair/8.jpg',
    './images/furniture/bed/8.jpg',
    './images/furniture/sofa/8.jpg',
    './images/furniture/dining/8.jpg',
    './images/furniture/table/8.jpg',
    './images/furniture/chair/9.jpg',
    './images/furniture/bed/9.jpg',
    './images/furniture/sofa/9.jpg',
    './images/furniture/dining/9.jpg',
    './images/furniture/table/9.jpg',
  ],
  topRated: [
    './images/furniture/chair/10.jpg',
    './images/furniture/bed/10.jpg',
    './images/furniture/sofa/10.jpg',
    './images/furniture/dining/10.jpg',
    './images/furniture/table/10.jpg',
    './images/furniture/chair/11.jpg',
    './images/furniture/bed/11.jpg',
    './images/furniture/sofa/11.jpg',
    './images/furniture/dining/11.jpg',
    './images/furniture/table/11.jpg',
    './images/furniture/chair/12.jpg',
    './images/furniture/bed/12.jpg',
    './images/furniture/sofa/12.jpg',
    './images/furniture/dining/12.jpg',
    './images/furniture/table/12.jpg',
  ],
};

export default imagesByCategory;
